version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: socialmediadb
    ports:
      - "5432:5432"
    networks:
      - socialmedia-network

  social-media:
    image: social-media:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - socialmedia-network

networks:
  socialmedia-network:
    driver: bridge
